version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - type: bind
        source: ./tmp/db
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        RUBYGEMS_VERSION: "3.3.20"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3010 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
    environment:
      - RAILS_ENV=production
      - DB_USERNAME=backend
      - DB_PASSWORD=admin
    ports:
      - "3010:3010"
    depends_on:
      - db
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    ports:
      - "3000:3000"
