databases:
  - name: recipe_choice_db
    databaseName: backend_production_zelz
    user: backend_production_zelz_user
    region: singapore

services:
  - type: web
    name: backend_production_zelz_user
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
  - key: DATABASE_URL
    fromDatabase:
      name: recipe_choice_db
      property: connectionString
  - key: RAILS_MASTER_KEY
    sync: false
